before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./cmd/dash
    binary: dash
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - README.md
      - config.yml
      - front/dist
      - resources

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
