auth:
  username: admin
  password: flexx

game:
  board: "http://127.0.0.1:8000"
  end: "2020-12-24 14:00:00+03:00"

vulnboxes:
  - user: cbs
    host: 127.0.0.1
    goxy_port: 8000
    services:
      - name: base_http
        port: 5000
        proto: http

farm:
  addr: 127.0.0.1:5137

mongol:
  addr: 127.0.0.1:5138

neo:
  addr: 127.0.0.1:5005
  version: '2.0-beta.7'
