auth:
  username: admin
  password: flexx

game:
  board: "http://127.0.0.1:8000"
  end: "2020-12-24 14:00:00+03:00"

vulnboxes:
  - user: cbs
    host: 127.0.0.1
    services: [ base_http ]
    goxy_port: 8000

services:
  - name: base_http
    port: 5000
    proto: http

farm:
  addr: 127.0.0.1:5137

mongol:
  addr: 127.0.0.1:5138

start_sploit: resources/start_sploit.py
key_file: resources/ssh_key